###
### Cliente John Doe

POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@j.com"
}

### Cliente Jane Doe

POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
  "name": "Jane Doe",
  "email": "jane@j.com"
}

### Conta do John Doe

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
  "client_id": "761360ee-44e7-48b6-84b0-fa3972315878"
}

### Conta da Jane Doe

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
  "client_id": "fa88867f-457b-408b-8c4e-80baf256dc36"
}

### Transacao do John Doe para Jane Doe

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
  "account_id_from": "7e34e7ef-62e6-48a5-a74c-bc1d69a9fa2a",
  "account_id_to": "bbc3fde5-bef0-4537-8381-1b084a84735f",
  "amount": 100
}

